### ISSUE TITLE
statistics.js sortIt()

### ISSUE THREAD

**Issue by jansule** [gs2-2/paper.hub#18]
Wenn man die flot.html im Browser öffnet und im Slider einen Bereich auswählt werden Statistiken und Histogramm angezeigt. Wenn man allerdings mehrmals hintereinander verschiedene Bereiche auswählt, werden die Daten im Hauptplot verändert. Der Plot wird nun sortiert dargestellt.

Eigentlich darf das nicht passieren, vor allem, weil ich am Hauptplot keine Änderungen vornehme (zoomen verändert den Plot nicht, ist getestet). Das Problem scheint in der Funktion sortIt() in der statistics.js zu liegen. Hier erzeuge ich ein neues Array mit den sortierten Einträgen. Dieses verwende ich für das Plotten des Histogramms und zur Berechnung der Statistiken. Ich denke, hier liegt irgendwo ein Call-By-Reference Error vor und die original Daten werden überschrieben. Ich habe den Fehler aber noch nicht gefunden.
Darum wäre es super, wenn ihr auch mal darüber schaut. 

Alles spielt sich im js-Teil der flot.html und in der statistics.js ab. 

PS: Das Array, auf welches sortIt() angewandt wird heißt "selection" und wird in der flot.html in den Zeilen 204-223 erzeugt

**Comment by noerw** [comment]
[`statistics.js`](https://github.com/gs2-2/paper.hub/blob/cf19b685882b36bff127f193ae5539185d56f826/public/js/statistics.js#L100-L123), [`flot.html`](https://github.com/gs2-2/paper.hub/blob/cf19b685882b36bff127f193ae5539185d56f826/public/flot.html#L245).

In JS werden Basistypen _by value_ an Funktionen übergeben, Arrays & Objekte aber _by reference_.
dh, du sortierst das originalarray.
dh, in der fkt `sortIt()` sollte am anfang sowas in der art stehen, damit ne kopie erzeugt wird:

```
var sorted = unsorted.slice();
...
```

Das Problem mag noch an anderen Stellen auftreten, danach hab ich jetzt nicht geschaut. Deshalb wärs klug, die Kopie am anfang der statistikberechnung zu erstellen, sodass die Verwechslungsgefahr möglichst gering ist

**Comment by jansule** [comment]
Hab das jetzt auf andere Art geregelt. Ich erstelle jetzt nur ein Array mit den y-Werten. Die x-Werte werden sowieso nicht gebraucht. So kann für temporal und spatial Data die gleiche Funktion verwendet werden.
Hab es getestet und es klappt.
Danke für den Tipp!
